### ISSUE TITLE
Proxy not connected

### ISSUE THREAD

**Issue by SWAPAIEXPERT** [clue/reactphp-http-proxy#51] opened 2023-06-20 13:02 UTC
Hello team,

I want to check if the email address exists or not, I have used the below script using proxy detail. 
I have tried many proxies but not working and returning an error as "Error: Connection to tcp://alt3.aspmx.l.google.com:587 failed because proxy refused the connection with HTTP error code 403 (Forbidden) (ECONNREFUSED)", So could you plz suggest a proxy which supports to this.

```
require __DIR__ . '/../vendor/autoload.php';
 
$url = getenv('http_proxy');
if ($url === false) {
    $url = '[ttmngjxo:2xiehi9i68nl@2.56.119.93:5074](mailto:ttmngjxo:2xiehi9i68nl@2.56.119.93:5074)';
}
 
$proxy = new Clue\React\HttpProxy\ProxyConnector($url);
 
$connector = new React\Socket\Connector(array(
    'tcp' => $proxy,
    'timeout' => 3.0,
    'dns' => false
));
 
$connector->connect('tcp://alt3.aspmx.l.google.com:587')->then(function (React\Socket\ConnectionInterface $connection) {
    $connection->write("EHLO local\r\n");
               $connection->write("MAIL FROM:[test@gmail.com](mailto:test@gmail.com)\r\n");
               $connection->write("RCPT TO:[skumbhar1@hghfhgfhgf.com](mailto:skumbhar1@hghfhgfhgf.com)\r\n");
               $connection->write("RSET\r\n");
    $connection->on('data', function ($chunk) use ($connection) {
        echo $chunk."<br/><br/><br/>";
        $connection->write("QUIT\r\n");
    });
}, function (Exception $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
});
```

**Comment by SimonFrings** [comment] 2023-06-21 14:29
Thanks for bringing this up :+1:

I'm not 100% sure, but I think this is caused by the proxy you're using. As the documentation in this project says:
>While many (public) HTTP CONNECT proxy servers often limit this to HTTPS port 443 only, this can technically be used to tunnel any TCP/IP-based protocol (HTTP, SMTP, IMAP etc.)

If this is the case here and your current proxy only supports port 443, you should try a different proxy which supports protocols like SMTP. Have you already tried different proxies?

Please let me know if this solves your problem :)

**Comment by SimonFrings** [comment] 2023-07-03 13:01
I believe this ticket is answered, so I will close this for now. We can reopen this if you encounter the same issues again after trying out the solutions mentioned in here. If you do need to reopen the ticket, please provide some information about the steps you've taken so far, what worked and what didn't.

**Closed as completed by SimonFrings** 2023-07-03 13:01 UTC
Labels: question
