### ISSUE TITLE
when use pipe it seem do not work

### ISSUE THREAD

**Issue by wpjscc** [clue/reactphp-http-proxy#52] opened 2023-10-09 07:32 UTC
it can print 222222 but not print 77777777777

<img width="404" alt="image" src="https://github.com/clue/reactphp-http-proxy/assets/76907477/56cf3b4d-feda-4146-af28-eacf77ad4a71">

```
$proxy = new Clue\React\HttpProxy\ProxyConnector('127.0.0.1:8080');

$connector = new React\Socket\Connector(array(
    'tcp' => $proxy,
    'dns' => false
));
$connector->connect($uri)->then(function($proxyConnection) use ($connection) {
   $proxyConnection->on('data', function ($chunk) use ($connection,$proxyConnection) {
        var_dump($chunk, 222222, $connection->isWritable(), $connection->isReadable(), $proxyConnection->isWritable(), $proxyConnection->isReadable());
    });
    $connection->pipe($proxyConnection);
    $proxyConnection->pipe(new ThroughStream(function ($data) {
        var_dump($data, 77777777777);
        return $data;
    }))->pipe($connection);
});


```

**Comment by SimonFrings** [comment] 2024-04-10 08:43
Hey @wpjscc, thanks for bringing this up :+1:

This can have multiple reasons, but unfortunately I can't see the fullness of your code, so I can only make some assumptions here. One reason could be that the `ThroughStream` is missing its namespace, so PHP doesn't know where this class comes from and throws an exception. This all is happening inside a promise and if you're installing [Promise](https://github.com/reactphp/promise/tree/3.x) in [v2](https://github.com/reactphp/promise/tree/2.x) or [v1](https://github.com/reactphp/promise/tree/1.x), they will swallow exceptions and errors (we changed this with the release of [Promise v3](https://github.com/reactphp/promise/releases/tag/v3.0.0)).  You can try to add a rejection handler to your `then()` to at least see if there's an exception thrown, see https://github.com/reactphp/promise?tab=readme-ov-file#promiseinterfacethen.

If this isn't the case, please provide a bit more information to help find the cause of this. I hope this helps :+1:

I think this should answer your question, so I will close this ticket for now. We can reopen this if you encounter the same issues again after trying out the solutions mentioned in here. If you do need to reopen the ticket, please provide some information about the steps you've taken so far, what worked and what didn't.

**Closed as completed by SimonFrings** 2024-04-10 08:43 UTC
Labels: question
